---
- name: Initialize Array
  set_fact:
    jboss_server_instance_id: []
    jboss_server_instance_public_ip: []

- name: Create JBoss EAP Server 1
  amazon.aws.ec2_instance:
    name: "{{ jboss_server_1 }}"
    key_name: "{{ aws_key_name }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id_vm1 }}"
    instance_type: "{{ aws_instance_type }}"
    security_group: "{{ aws_security_group }}"
    network:
      assign_public_ip: true
    image_id: "{{ aws_image_id }}"
    region: "{{ aws_region }}"
    state: running
    wait: true
  register: jboss_1_vm_info

- name: Update Array
  set_fact:
    jboss_server_instance_id: "{{ jboss_server_instance_id + [jboss_1_vm_info.instances[0].instance_id] }}"
    jboss_server_instance_public_ip: "{{ jboss_server_instance_public_ip + [jboss_1_vm_info.instances[0].public_ip_address] }}"

- name: Create JBoss EAP Server 2
  amazon.aws.ec2_instance:
    name: "{{ jboss_server_2 }}"
    key_name: "{{ aws_key_name }}"
    vpc_subnet_id: "{{ aws_vpc_subnet_id_vm2 }}"
    instance_type: "{{ aws_instance_type }}"
    security_group: "{{ aws_security_group }}"
    network:
      assign_public_ip: true
    image_id: "{{ aws_image_id }}"
    region: "{{ aws_region }}"
    state: running
    wait: true
  register: jboss_2_vm_info

- name: Update Array
  set_fact:
    jboss_server_instance_id: "{{ jboss_server_instance_id + [jboss_2_vm_info.instances[0].instance_id] }}"
    jboss_server_instance_public_ip: "{{ jboss_server_instance_public_ip + [jboss_2_vm_info.instances[0].public_ip_address] }}"

- name: Save information of array for subsequent workflow
  set_stats:
    data:
      jboss_eap_hostname: "{{ [jboss_server_1] + [jboss_server_2] }}"
      jboss_eap_instance_id: "{{ jboss_server_instance_id }}"
      jboss_eap_instance_public_ip: "{{ jboss_server_instance_public_ip }}"
