---
- name: Create and Customize VMware Instance
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vmware_datacenter }}"
    cluster: "{{ vmware_cluster }}"
    folder: "/{{ vmware_datacenter }}/vm"
    validate_certs: no
    name: "{{ vm_name }}"
    template: "{{ vm_template }}"
    state: poweredon
    disk:
    - size_gb: "{{ disk_size }}"
      type: thin
      datastore: "{{ vmware_datastore }}"
    hardware:
      memory_mb: "{{ vm_memory }}"
      num_cpus: "{{ vm_cpu }}"
    networks:
    - name: "{{ vm_network }}"
      start_connected: true
      ip: "{{ vm_ip }}"
      netmask: "{{ vm_network_netmask }}"
      gateway: "{{ vm_network_gateway }}"
      domain: "{{ network_domain }}"
      dns_servers: "{{ vm_dns_server }}"
    wait_for_ip_address: true
    customization:
      domain: "{{ network_domain }}"
      dns_servers:
        - "{{ vm_dns_server }}"
      hostname: "{{ vm_name }}"
      password: '{{ vm_password }}'
    wait_for_customization: true
