---
- name: Add Host to Inventory
  hosts: localhost
  become: no
  gather_facts: no
  vars:
    coolstore_inventory: coolstore-demo

  roles:
    - add_jboss_eap_to_inventory
    - add_postgresql_to_inventory
