---
- name: Add Host to Inventory
  hosts: localhost
  become: no
  gather_facts: no
  vars:
    host_name: "{{ jboss_eap_instance_id }}"
    coolstore_inventory: coolstore-demo
    host_ip: "{{ jboss_eap_instance_public_ip }}"

  roles:
    - add_host_to_inventory
