---
- name: Perform Healthcheck on Endpoint
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Wait for Application Load Balancer to be ready and Perform Endpoint Check
      ansible.builtin.uri:
        url: "{{ coolstore_app_endpoint }}"
      register: _result
      until: _result.status == 200
      retries: 12
      delay: 10
