---
- name: Deploy coolstore application
  hosts: jboss
  remote_user: ec2-user
  become: yes
  gather_facts: no
  vars:
    app_deployment_path: "/opt/jboss-eap-7.4/standalone/deployments/"

  roles:
    - deploy_coolstore_app
