---
- name: Deploy Postgresql
  hosts: "{{ postgresql_hostname[0] }}"
  remote_user: ec2-user
  become: yes
  gather_facts: no
  vars:
    database: coolstore
    database_user: ansible
    database_user_password: ansible
    postgres_user_password: postgres

  roles:
    - deploy_postgresql
