---
- name: Deploy EC2 Instances
  hosts: localhost
  become: no
  gather_facts: no
  vars:
    aws_access_key: xyz
    aws_image_id: ami-xyz
    aws_instance_type: t2.medium
    aws_key_name: aws-ec2
    aws_region: ap-southeast-1
    aws_secret_key: xyz
    aws_security_group: sg-xyz
    aws_vpc_subnet_id: subnet-xyz
    servers_to_be_deployed: ['jboss-eap-1','jboss-eap-2','postgresql-1']

  roles:
    - deploy_ec2_instances
