---
- name: Deploy and Configure JBoss EAP Servers
  hosts: jboss
  remote_user: ec2-user
  become: yes
  gather_facts: no
  vars:
    app_database: "coolstore"
    app_database_user: "ansible"
    app_database_user_password: "ansible"
    aws_access_key: abc
    aws_bucket_name: coolstore-jboss-eap-7.4
    aws_object_name: jboss-eap-7.4.0.zip
    aws_region: ap-southeast-1
    aws_secret_key: xyz
    jboss_eap_directory: "/opt/jboss-eap-7.4"

  roles:
    - deploy_jboss_eap_server
